### ISSUE TITLE
Find a way to get content of the page as a stream

### ISSUE THREAD

**Issue by GabLeRoux** [GabLeRoux/ansi-colors-chrome-extension#1]
This project has been blocked for a while, I couldn't find a way to get content of the page as as stream. This is probably the only step before being able to call `ansi-html-stream`.

This is the readme section that says:

> figure out how to pass data to [ansi-html-stream](https://github.com/hughsk/ansi-html-stream) (using a stream? maybe I should find a different solution)

Next step will be to update dom document with other end of the stream!

**Comment by maxgalbu** [comment]
Hey, you could use https://github.com/rburns/ansi-to-html instead, doesn't require a stream

**Comment by GabLeRoux** [comment]
Thanks for sharing, I'll definitely give this a try :tada:

**Comment by maxgalbu** [comment]
Tried and it nearly freezes chrome, the window becomes unresponsive... don't what happens...

**Comment by maxgalbu** [comment]
https://github.com/GabLeRoux/ansi-colors-chrome-extension/pull/9

**Comment by GabLeRoux** [comment]
Closed with #9 thanks!
