### ISSUE TITLE
Why is this not published on Google Chrome WebStore?

### ISSUE THREAD

**Issue by ssbarnea** [GabLeRoux/ansi-colors-chrome-extension#5]
I find the idea of this plugin really useful but I am somehow surprised that is was not published on WebStore. Why?

**Comment by GabLeRoux** [comment]
Oh thanks, it's pretty much because I still don't have a solution for #1, but I could still publish this to the chrome store. I wish there was more attention on this extension so maybe someone could find a solution.

Someone asked how to install it in #2 so maybe it's time to publish it anyway :)

**Comment by GabLeRoux** [comment]
Published here: https://chrome.google.com/webstore/detail/hpkomngllcnigoocaolicfknnhibnmfi/

> Your item is in the process of being published and may take up to 60 minutes to appear in the Chrome Web Store. 

You managed to convince me. I had to pay $5USD but now I have no more reasons for not publishing my chrome extension(s) 🍻

**Comment by ssbarnea** [comment]
Those $5 may be one of the best investments, believe me. There are few similar extensions already but I will pick the best one and and become a permanent contributor.

I need this a solution for allowing people to read ANSI colors logs from CI and if I can do it without having to convert ansi2html server side it would much better: considerably less data to transfer, which translates to better speed.

**Comment by GabLeRoux** [comment]
Awesome, that was indeed kind of my use case. I had to deal with some output from jenkins, but I managed to install this instead: https://wiki.jenkins.io/display/JENKINS/AnsiColor+Plugin

I don't know about your CI, maybe there's something similar. I will be happy to add you as a contributor if you want to give a hand.
