### ISSUE TITLE
colors are stripped instead of being applied

### ISSUE THREAD

**Issue by ssbarnea** [GabLeRoux/ansi-colors-chrome-extension#7]
It seems that ANSI colors are stripped instead of being colored.

**Comment by GabLeRoux** [comment]
Duplicates #1 that's exactly what I wanted to do first. I found a node module that does just that and I was able to browserify it, but I can't manage to pass the current page as a stream.

**Comment by GabLeRoux** [comment]
Fixed with #9 👍
